// Las 18 fichas editoriales del catálogo: 14 comandos reales de `agente-qa-mcp` + 4 operaciones
// que todavía no tienen comando (Redactar/Generar/Ejecutar/Reparar). `catalogo.ts` cruza esto con
// `cli.generado.json`; `catalogo.test.ts` es el guard que impide que las dos copias se desincronicen.
import type { EjesFicha, FichaComando } from "./tipos";

const EJE_CONFIG: EjesFicha = { conductor: "humano", agente: "ninguno", coste: "cero", estado: "construido" };
const EJE_DETERMINISTA_SIN_AGENTE: EjesFicha = { conductor: "determinista", agente: "ninguno", coste: "cero", estado: "construido" };
const EJE_MAPEADOR_DETERMINISTA: EjesFicha = { conductor: "determinista", agente: "mapeador-mcp", coste: "cero", estado: "construido" };
const EJE_MAPEADOR_HUMANO: EjesFicha = { conductor: "humano", agente: "mapeador-mcp", coste: "cero", estado: "construido" };
const EJE_MAPEADOR_LLM: EjesFicha = { conductor: "llm-api", agente: "mapeador-mcp", coste: "facturado", estado: "construido" };

export const COMANDOS: FichaComando[] = [
  // ── Configuración ──────────────────────────────────────────────────────────────────────
  {
    ruta: ["config"],
    pestana: "Configuración",
    unaLinea: 'Configura la modalidad de LLM del proyecto: "api" (proveedor+modelo+clave) o "suscripcion" (Claude Code).',
    queHace: [
      'Pregunta, en orden, la modalidad ("api" o "suscripcion"). Con "suscripcion" no pregunta nada más: usa el binario `claude` de la máquina, sin proveedor ni modelo propios.',
      'Con "api" pregunta además proveedor (Anthropic, OpenAI, Google o Groq), modelo y clave de API — nunca varias combinaciones a la vez: una sola modalidad activa por proyecto.',
      "La modalidad se guarda en `llm` de `config.json` del proyecto (versionable); la clave de API, aparte, en el `.env` global de `agente-qa-mcp`.",
    ],
    queDeja: ["`llm` en `config.json` del proyecto actual; con modalidad `api`, además la clave en el `.env` global de `agente-qa-mcp`."],
    cuandoUsarlo: ["La primera vez que inicializas un proyecto con `init`.", "Para cambiar de modalidad, de proveedor o de modelo."],
    cuandoNo: [
      "Para ver la configuración ya guardada sin tocarla — usa `config --show`.",
      "Para credenciales de la propia app bajo prueba (usuario/contraseña de login) — eso va en `.agente-qa/.env` del proyecto, lo crea `init`.",
    ],
    opciones: {
      "--show": { matiz: "Solo lectura: no pregunta nada, imprime la modalidad resuelta (con `api`, la clave censurada a los 4 últimos caracteres)." },
      "--modalidad": { matiz: 'Fija la modalidad ("api" o "suscripcion") sin pasar por la pregunta interactiva.' },
      "--proveedor": { matiz: "Solo con modalidad api: fija el proveedor sin pasar por la pregunta interactiva." },
      "--modelo": { matiz: "Solo con modalidad api: fija el modelo sin pasar por la pregunta interactiva." },
      "--api-key": { matiz: "Solo con modalidad api: fija la clave sin pasar por la pregunta interactiva." },
    },
    ejemplos: [
      { texto: "config --show", explica: "Mira la modalidad ya configurada sin cambiar nada.", plantilla: true },
      { texto: "config --modalidad suscripcion", explica: "Cambia a la suscripción de Claude Code, sin preguntar nada más.", plantilla: true },
    ],
    notas: [
      { tipo: "ok", texto: "No hace falta repetirlo entero si solo cambia un dato: cada flag se puede usar suelto." },
      { tipo: "aviso", texto: "Sin flags es interactivo: no sirve dentro de un script no interactivo — usa los flags o `--show`." },
    ],
    ejes: EJE_CONFIG,
    palabrasClave: ["configuración", "modalidad", "api", "suscripcion", "claude", "proveedor", "modelo", "clave", "api key"],
    // Verificado en `src/cli/commands/config.ts`: la acción decide `options.show ? runShow() :
    // runInteractive(options)` — con `--show`, `runShow()` no recibe ningún otro flag, así que
    // cualquiera de estos junto a `--show` se ignora en silencio, nunca "además muestra y cambia".
    incompatibles: [
      ["--show", "--modalidad"],
      ["--show", "--proveedor"],
      ["--show", "--modelo"],
      ["--show", "--api-key"],
    ],
  },
  {
    ruta: ["init"],
    pestana: "Configuración",
    unaLinea: "Prepara una carpeta como proyecto de agente-qa-mcp: crea .agente-qa/ con su configuración, mapa y estado vacíos.",
    queHace: [
      "Crea `.agente-qa/` con `config.json`, `.env`, y las carpetas `map/`, `features/`, `state/`, además de `memory.json` y un `.gitignore` que evita subir secretos y estado de sesión.",
      "Pregunta la URL de la aplicación y el entorno (`dev`/`test`/`staging`/`production`) si no se dan por flag; con `--yes` no pregunta nada y exige que los dos flags vengan puestos.",
      "Relanzarlo sobre una carpeta que ya tiene `.agente-qa/` no toca nada — lo dice y no sobrescribe.",
    ],
    queDeja: [
      "`.agente-qa/config.json` — URL y entorno del proyecto.",
      "`.agente-qa/.env` — vacío, para las credenciales de la app bajo prueba (nunca versionado).",
      "`.agente-qa/map/`, `.agente-qa/features/`, `.agente-qa/state/` — vacíos, los rellenan los agentes siguientes.",
    ],
    cuandoUsarlo: ["Al empezar a mapear una aplicación nueva."],
    cuandoNo: [
      "Sobre una carpeta que ya es un proyecto — no hace falta, y no cambia nada si lo relanzas.",
      "Con `\"environment\": \"production\"` sin estar seguro: ese valor restringe login y escrituras en el resto de comandos que lo respetan.",
    ],
    opciones: {
      "--url": { matiz: "Evita la pregunta de URL; junto con --env y --yes permite un init totalmente no interactivo." },
      "--env": { matiz: "Uno de dev/test/staging/production; production es el que más restringe login y escrituras en el resto de comandos." },
      "--yes": { matiz: "No pregunta nada: si falta --url o --env, falla en vez de preguntar (pensado para scripts)." },
    },
    ejemplos: [
      { texto: "init --url <url> --env test --yes", explica: "Crea el proyecto sin ninguna pregunta interactiva.", plantilla: true },
      { texto: "init", explica: "Crea el proyecto preguntando la URL y el entorno.", plantilla: true },
    ],
    notas: [
      { tipo: "ok", texto: "Es seguro relanzarlo: si `.agente-qa/` ya existe, no toca nada." },
      { tipo: "aviso", texto: "El entorno `production` cambia el comportamiento de `map`/`record`: login y escrituras se restringen más." },
    ],
    ejes: EJE_CONFIG,
    palabrasClave: ["init", "inicializar", "proyecto", "carpeta", "url", "entorno", "production"],
    incompatibles: [],
  },
  {
    ruta: ["doctor"],
    pestana: "Configuración",
    unaLinea: "Revisa que la configuración y el proyecto actual están listos para trabajar, sin tocar nada.",
    queHace: [
      "Comprueba, uno por uno: la versión de Node, que la modalidad de LLM del proyecto resuelva bien (con `api`, proveedor+modelo y clave válidos; con `suscripcion`, que `claude` esté en el PATH), y que el proyecto actual tenga `.agente-qa/` inicializado.",
      "Cada comprobación que falla dice exactamente qué falta y cómo arreglarlo — nunca solo un ✗ sin contexto.",
    ],
    queDeja: [],
    cuandoUsarlo: ["Después de instalar o reconfigurar, antes de lanzar cualquier otro comando.", "Cuando algo falla y no está claro si es de configuración o del proyecto."],
    cuandoNo: ["No cambia nada: si necesitas arreglar algo, `doctor` solo te dice qué — el arreglo va por `config`/`init`."],
    opciones: {},
    ejemplos: [{ texto: "doctor", explica: "Repasa configuración y proyecto de un vistazo.", plantilla: true }],
    notas: [{ tipo: "ok", texto: "Gratis y casi sin red: solo comprueba que las claves resuelven de verdad." }],
    ejes: EJE_DETERMINISTA_SIN_AGENTE,
    palabrasClave: ["doctor", "diagnóstico", "salud", "comprobar", "claude", "path"],
    incompatibles: [],
  },
  {
    ruta: ["llm", "ping"],
    pestana: "Configuración",
    unaLinea: "Manda un mensaje mínimo al proveedor configurado, para confirmar que la clave y el modelo funcionan.",
    queHace: [
      "Llama a la modalidad configurada del proyecto (solo tiene sentido con `api`: `suscripcion` no pasa por aquí) con una herramienta de juguete y muestra la respuesta, los tokens gastados, el coste y la duración.",
      "`--provider`/`--model` fuerzan un proveedor o modelo concreto por encima de la modalidad configurada, para probar una combinación sin cambiar la configuración guardada.",
    ],
    queDeja: [],
    cuandoUsarlo: ["Tras configurar un proveedor nuevo, para confirmar que la clave funciona antes de lanzar algo más largo.", "Para comparar coste/latencia entre dos modelos sin tocar `config`."],
    cuandoNo: ["Para navegar o mapear nada — no abre navegador, solo habla con el LLM."],
    opciones: {
      "--provider": { matiz: "Fuerza el proveedor por encima de la modalidad configurada, usando igualmente la clave guardada de ese proveedor." },
      "--model": { matiz: "Fuerza el modelo; útil para probar uno fuera de la tabla de precios (avisa si no conoce el coste, sin fallar)." },
      "--no-metrics": { matiz: "Esta llamada de prueba no queda en `metrics` — útil para no ensuciar el historial con pings." },
    },
    ejemplos: [
      { texto: "llm ping", explica: "Prueba la modalidad tal cual está configurada en el proyecto.", plantilla: true },
      { texto: "llm ping --provider groq", explica: "Prueba Groq en vez del proveedor configurado.", plantilla: true },
    ],
    notas: [{ tipo: "aviso", texto: "Gasta tokens reales del proveedor configurado (facturado, aunque sea el mínimo)." }],
    ejes: { conductor: "llm-api", agente: "ninguno", coste: "facturado", estado: "construido" },
    palabrasClave: ["llm", "ping", "probar", "proveedor", "modelo", "clave", "api key"],
    incompatibles: [],
  },
  {
    ruta: ["validate"],
    pestana: "Configuración",
    unaLinea: "Valida un map.json contra el esquema publicado del contrato, sin lanzar nunca un stack trace.",
    queHace: [
      "Comprueba que el fichero indicado cumple el esquema Zod de `agente-qa-contract`. Si es válido, dice cuántas pantallas y localizadores tiene; si no, señala la ruta exacta del campo que lo rompe (p.ej. `screens[0].locators[0].count`).",
      "También cubre los casos de fichero inexistente o que no es JSON válido, con un mensaje legible en vez de una traza de Node.",
    ],
    queDeja: [],
    cuandoUsarlo: ["Después de cualquier comando que escriba en `map.json` (`snapshot`, `record`, `map`, `run`), para confirmar que sigue siendo válido.", "Al revisar un `map.json` editado a mano."],
    cuandoNo: ["No repara nada — solo diagnostica. El arreglo es volver a mapear la pantalla afectada."],
    opciones: {},
    ejemplos: [{ texto: "validate .agente-qa/map/map.json", explica: "Comprueba el mapa del proyecto actual.", plantilla: true }],
    notas: [{ tipo: "ok", texto: "No abre navegador ni gasta nada: es una comprobación puramente local." }],
    ejes: EJE_DETERMINISTA_SIN_AGENTE,
    palabrasClave: ["validate", "validar", "map.json", "esquema", "contrato"],
    incompatibles: [],
  },
  // ── Dashboard ──────────────────────────────────────────────────────────────────────────
  {
    ruta: ["metrics"],
    pestana: "Dashboard",
    unaLinea: "Enseña las últimas llamadas al LLM registradas — o borra la base de métricas.",
    queHace: [
      "Lista las últimas N llamadas (20 por defecto) con proveedor, modelo, tokens, coste y duración, y un total agregado.",
      "`--reset` borra el histórico completo, pidiendo confirmación antes; `--json` cambia la forma de la salida a las filas crudas de `runs`/`run_events` en vez del listado de llamadas.",
    ],
    queDeja: [],
    cuandoUsarlo: ["Para ver cuánto ha costado explorar hasta ahora, o comparar el coste entre proveedores."],
    cuandoNo: ["Para ver una corrida en vivo mientras corre — eso lo hace la propia pestaña Explorar leyendo el NDJSON de `--json`, no `metrics`."],
    opciones: {
      "--last": { matiz: "Cuántas llamadas mostrar, no cuántos días — el valor por defecto es 20." },
      "--reset": { matiz: "Destructivo: pide confirmación por consola antes de vaciar la base de métricas entera." },
      "--json": { matiz: "No es el `--json` global de NDJSON en vivo: con --last imprime el histórico ya guardado como JSON, de una sola vez." },
    },
    ejemplos: [
      { texto: "metrics --last 20", explica: "Ve las últimas 20 llamadas y el total gastado.", plantilla: true },
      { texto: "metrics --reset", explica: "Vacía el histórico de métricas (pide confirmación).", plantilla: true },
    ],
    notas: [{ tipo: "peligro", texto: "--reset borra el histórico entero sin forma de deshacerlo tras confirmar." }],
    ejes: EJE_DETERMINISTA_SIN_AGENTE,
    palabrasClave: ["metrics", "métricas", "coste", "historial", "llamadas", "tokens", "reset"],
    // Verificado en `src/cli/commands/metrics.ts`: la acción hace `options.reset ? runReset() :
    // json ? runListJson(last) : runList(last)` — con `--reset`, ni `--last` ni `--json` se leen.
    incompatibles: [
      ["--reset", "--last"],
      ["--reset", "--json"],
    ],
  },
  // ── Explorar ───────────────────────────────────────────────────────────────────────────
  {
    ruta: ["browse"],
    pestana: "Explorar",
    unaLinea: "Abre un navegador real y enseña por consola lo que vería el LLM de esa pantalla, sin gastar ningún token.",
    queHace: [
      "Navega a la URL indicada y muestra una frase resumen más una lista corta de elementos interactivos (botones, campos, enlaces), cada uno con su `ref` — el mismo resumen compacto que recibiría el LLM en el bucle agéntico.",
      "`--detail` añade el snapshot técnico crudo y el tamaño en caracteres de ambos, para comprobar cuánto más pequeño es el resumen (más de 10 veces, típicamente).",
    ],
    queDeja: [],
    cuandoUsarlo: ["Para ver, antes de gastar nada, si una pantalla es legible para el agente o le va a costar.", "Para depurar por qué `map`/`snapshot` no encuentran un elemento — mira si aparece en la lista."],
    cuandoNo: ["No escribe nada en `map.json` — para eso está `snapshot`."],
    opciones: {
      "--headed": { matiz: "Muestra la ventana real en vez de correr sin cabeza; más lento, útil para ver qué pasa." },
      "--detail": { matiz: "Añade el snapshot crudo completo — solo para depurar, es mucho más largo que el resumen." },
      "--json": { matiz: "Es un volcado del PageSummary como JSON, no un flujo NDJSON de eventos (ese es el --json global de map/run/record/snapshot)." },
    },
    ejemplos: [{ texto: "browse <url> --headed", explica: "Mira una pantalla con el navegador visible.", plantilla: true }],
    notas: [
      { tipo: "ok", texto: "Coste cero: no llama a ningún LLM." },
      { tipo: "aviso", texto: "Requiere `npx playwright install chromium` una vez, si nunca se ha usado ningún comando de navegador." },
    ],
    ejes: EJE_MAPEADOR_HUMANO,
    palabrasClave: ["browse", "navegador", "ver", "resumen", "página"],
    incompatibles: [],
  },
  {
    ruta: ["snapshot"],
    pestana: "Explorar",
    unaLinea: "Escribe o actualiza map.json con la pantalla actual, con localizadores verificados en vivo contra el navegador — sin ningún LLM.",
    queHace: [
      "Navega a la URL, lee la pantalla real y anota cada campo/botón con la instrucción exacta para encontrarlo en un test (`page.getByRole(...)`, etc.), verificada una a una (`count === 1`) antes de guardarla.",
      "Si varias cosas se parecen y no puede distinguirlas con seguridad, las deja marcadas como dudosas en vez de inventar cuál es.",
      "Relanzarlo sobre la misma URL reemplaza esa pantalla entera (no la duplica) y añade una entrada a `coverage[]`.",
    ],
    queDeja: ["`.agente-qa/map/map.json` — la pantalla nueva o actualizada, con localizadores verificados."],
    cuandoUsarlo: ["Para una pantalla suelta y estática, sin necesidad de que un LLM navegue para llegar a ella.", "Como paso de verificación rápida tras tocar el HTML de una pantalla."],
    cuandoNo: ["Para un flujo de varias pantallas encadenadas (login → panel) — eso es `record` o `map`."],
    opciones: {
      "--headed": { matiz: "Muestra la ventana real en vez de correr sin cabeza." },
      "--verificar-todo": { matiz: 'Verifica todos los elementos de la pantalla contra la cascada, en vez de dejarlos como "vistos" — más completo, más lento.' },
    },
    ejemplos: [{ texto: "snapshot <url>", explica: "Mapea esa pantalla suelta, sin cabeza.", plantilla: true }],
    notas: [{ tipo: "ok", texto: "Coste cero: no hay ningún LLM de por medio, solo lectura determinista del DOM." }],
    ejes: EJE_MAPEADOR_DETERMINISTA,
    palabrasClave: ["snapshot", "pantalla", "map.json", "localizadores", "verificar"],
    incompatibles: [],
  },
  {
    ruta: ["record"],
    pestana: "Explorar",
    unaLinea: "Graba un flujo hecho a mano en el navegador y lo convierte en pantallas verificadas del map.json.",
    queHace: [
      "Abre el navegador, tú haces el flujo a mano (login, rellenar algo, lo que quieras); al parar, cruza el código Playwright que generó la grabación con las pantallas por las que pasaste y verifica cada localizador contra el navegador real antes de guardarlo — nunca inventa uno.",
      "El localizador de cada elemento que pulsaste de verdad se recupera tal cual lo generó Playwright en ese instante (`strategy: \"recorded\"`), la máxima confianza posible.",
      "Con `--auto \"<objetivo>\"`, en vez de conducir tú, lo hace Claude Code (tu suscripción, vía `claude -p`) persiguiendo ese objetivo con las mismas herramientas de navegador — nunca código arbitrario — y pasa por la misma verificación que cualquier otra grabación.",
      "Tres formas de parar la grabación humana, ninguna privilegiada: una tecla en la consola, cerrar la ventana, o agotar `--max-duration` (15 min por defecto). Ctrl+C aborta sin guardar nada.",
    ],
    queDeja: ["`.agente-qa/map/map.json` — las pantallas que visitaste, con localizadores verificados, `validDataRecipe` si un envío funcionó, y `writeActions` de lo que intentaste enviar."],
    cuandoUsarlo: ["Para un flujo que sabes hacer a mano y quieres capturar exactamente como se hace (login, un formulario concreto).", "Con `--auto`, cuando quieres delegar ese mismo flujo en Claude Code en vez de hacerlo tú."],
    cuandoNo: ["Para explorar una app entera sin saber de antemano el camino — eso es `map --all`.", "`--raw` no escribe nada en el mapa: solo para ver el código Playwright crudo, no para poblar `map.json`."],
    opciones: {
      "--raw": { matiz: "Solo imprime el código Playwright grabado por consola; no toca map.json. Pensado para ver qué generaría Playwright antes de confiar en ello." },
      "--headed": { matiz: "Muestra la ventana real — casi obligatorio en grabación humana, si no ves nada que grabar." },
      "--max-duration": { matiz: "Tope de tiempo antes de que la grabación se pare sola; por defecto 15 minutos." },
      "--auto": {
        matiz: "En vez de conducir tú, Claude Code (tu suscripción, `claude -p`) persigue este objetivo en lenguaje libre.",
        ejes: { conductor: "claude-code", coste: "suscripcion" },
      },
      "--allow-writes": { matiz: "Solo tiene efecto con --auto: deja a Claude Code enviar formularios sin preguntar cada vez (nunca hace falta en production, ahí ya se permite con doble aviso)." },
      "--no-writes": { matiz: "Solo tiene efecto con --auto: Claude Code se queda en modo solo lectura, nunca hace clic ni escribe." },
      "--verificar-todo": { matiz: 'Verifica todos los elementos de cada pantalla, no solo los que tocaste durante la grabación — más completo, más lento.' },
    },
    ejemplos: [
      { texto: "record <url> --headed", explica: "Grabas tú el flujo a mano.", plantilla: true },
      { texto: 'record <url> --auto "<objetivo>"', explica: "Claude Code conduce el navegador por ti.", plantilla: true },
      { texto: "record <url> --raw --headed", explica: "Solo imprime el código Playwright, sin tocar el mapa.", plantilla: true },
    ],
    notas: [
      { tipo: "ok", texto: "La grabación humana no gasta ni un token: coste cero siempre." },
      { tipo: "aviso", texto: "--auto necesita el CLI `claude` en el PATH y con sesión iniciada — `doctor` lo comprueba." },
      { tipo: "peligro", texto: 'Con "environment": "production", --auto igual puede escribir (con doble aviso) — revisa el proyecto antes de usar --allow-writes ahí.' },
    ],
    ejes: EJE_MAPEADOR_HUMANO,
    palabrasClave: ["record", "grabar", "grabación", "auto", "claude code", "raw", "flujo"],
    // Verificado en `src/cli/commands/record.ts`: la acción rechaza con error si
    // `options.allowWrites === true && options.writes === false` (idéntico al de `map`, misma
    // línea de código).
    incompatibles: [["--allow-writes", "--no-writes"]],
  },
  {
    ruta: ["map"],
    pestana: "Explorar",
    unaLinea: "El LLM navega la app persiguiendo un objetivo y el código escribe map.json, dentro de topes de coste e iteraciones.",
    queHace: [
      'Le das un ámbito —`--goal "<texto>"` (un objetivo concreto), `--all` (tanto como sea razonable), `--units <ids>` (revisitar pantallas ya conocidas) o `--revisar` (solo repasar lo dudoso de un mapa ya existente)— y el LLM pulsa, escribe y se mueve de verdad, pero el mapa lo escribe siempre el programa, nunca la IA.',
      "Tres topes duros y terminales: `--max-cost`, `--max-iterations`, y detección de bucle vía `--max-repeated-action` (si repite la misma acción sin avanzar, para sola). Al terminar, sea como sea, el informe dice qué hizo y qué costó.",
      '`--login`/`--no-login`/`--fresh-session` controlan si intenta pasar el login antes de mapear; `--allow-writes`/`--no-writes` controlan si puede enviar formularios (nunca en `"environment": "production"`, pase lo que pase con el flag).',
      "`--ask` (combinable con `--revisar`) resalta en el navegador y pregunta por consola por cada elemento que el código no supo distinguir por su cuenta.",
    ],
    queDeja: ["`.agente-qa/map/map.json` — pantallas nuevas o actualizadas, cada una con la pasada (`coverage`) que la produjo.", "`.agente-qa/state/` — sesión guardada, si hubo login."],
    cuandoUsarlo: ["Para explorar zonas de la app que no sabes recorrer a mano, o para cubrir toda la app con `--all`.", "`--revisar` para arreglar los localizadores dudosos de un mapa viejo sin reexplorar nada."],
    cuandoNo: ["Para un flujo que ya sabes hacer a mano y quieres capturar exacto — ahí sale más barato `record`.", "`--goal`, `--all`, `--units` y `--revisar` son excluyentes entre sí: solo uno por corrida."],
    opciones: {
      "--goal": { matiz: "Excluyente con --all/--units/--revisar." },
      "--all": { matiz: "Sin objetivo concreto: explora tanto como sea razonable. Excluyente con --goal/--units/--revisar." },
      "--units": { matiz: "Solo revisita esos ids, sin tocar el resto del mapa. Excluyente con --goal/--all/--revisar." },
      "--revisar": { matiz: "No reexplora nada: solo repasa lo que ya está marcado como frágil o ambiguo. Excluyente con --goal/--all/--units. Si el mapa ya está limpio, ni abre el navegador." },
      "--ask": { matiz: "Tras la corrida, pregunta por consola lo que el código no supo distinguir; sin terminal interactiva no hace nada (lo dice en el informe)." },
      "--url": { matiz: "Si no se da, usa la de config.json del proyecto." },
      "--headed": {},
      "--max-cost": { matiz: "Tope en USD; al alcanzarlo, para y el mapa parcial sigue siendo válido." },
      "--max-iterations": { matiz: "Tope de vueltas del bucle; al alcanzarlo, para y lo dice en el informe." },
      "--max-repeated-action": { matiz: "Veces que se tolera la misma acción sin cambiar de pantalla antes de parar la corrida; 3 por defecto." },
      "--no-metrics": { matiz: "Esta corrida no queda registrada en metrics." },
      "--login": { matiz: "Intenta login por receta declarada o dejando que el agente la encuentre; en production se niega por completo salvo reutilizar una sesión ya guardada." },
      "--no-login": { matiz: "No intenta login aunque haya receta o credenciales disponibles." },
      "--fresh-session": { matiz: "Ignora la sesión guardada aunque siga fresca; fuerza login de nuevo." },
      "--allow-writes": { matiz: "Permite enviar formularios sin preguntar — nunca tiene efecto en production." },
      "--no-writes": { matiz: "No envía ningún formulario ni pregunta; el intento queda igual en writeActions[]." },
      "--verificar-todo": { matiz: 'Verifica todos los elementos de cada pantalla explorada en vez de dejarlos como "vistos" — más completo, más lento.' },
    },
    ejemplos: [
      { texto: 'map --goal "<objetivo>" --headed --max-cost 0.50', explica: "Explora un objetivo concreto con tope de gasto.", plantilla: true },
      { texto: "map --all --url <url>", explica: "Explora tanto como sea razonable de toda la app.", plantilla: true },
      { texto: "map --revisar --ask --headed", explica: "Repasa lo dudoso de un mapa ya existente y pregunta lo que no sabe distinguir.", plantilla: true },
    ],
    notas: [
      { tipo: "aviso", texto: "Facturado: cada iteración llama al LLM por API, con coste real." },
      { tipo: "peligro", texto: "En production nunca escribe ni hace login, aunque fuerces --allow-writes/--login." },
    ],
    ejes: EJE_MAPEADOR_LLM,
    palabrasClave: ["map", "mapear", "explorar", "goal", "objetivo", "all", "units", "revisar", "ask", "bucle"],
    // Verificado en `src/cli/commands/map.ts`: la acción cuenta cuántos de goal/all/units/revisar
    // llegaron y rechaza con error si hay más de uno (exactamente uno es obligatorio); y rechaza
    // por separado si `--allow-writes` y `--no-writes` llegan juntos.
    incompatibles: [
      ["--goal", "--all"],
      ["--goal", "--units"],
      ["--goal", "--revisar"],
      ["--all", "--units"],
      ["--all", "--revisar"],
      ["--units", "--revisar"],
      ["--allow-writes", "--no-writes"],
    ],
  },
  {
    ruta: ["run"],
    pestana: "Explorar",
    unaLinea: "Traduce una frase libre a un ámbito de map (goal/all/units) y hace exactamente lo mismo que map.",
    queHace: [
      "Recibe lo que quieres mapear en tu idioma normal, te enseña qué ha entendido (a qué pantallas o con qué objetivo) antes de arrancar, y ejecuta lo mismo que el `map` equivalente.",
      'Si lo que pides es en realidad grabar un flujo ("graba cómo doy de alta un registro"), abre el navegador para que lo hagas tú en vez de arrancar el bucle con IA.',
    ],
    queDeja: ["Igual que `map`: `.agente-qa/map/map.json` actualizado, con la pasada que corresponda."],
    cuandoUsarlo: ["Cuando no quieres pensar en `--goal`/`--all`/`--units` y prefieres pedirlo hablando normal."],
    cuandoNo: ["Si ya sabes exactamente el ámbito que quieres, `map` con el flag directo es más predecible."],
    opciones: {
      "--url": { matiz: "Si no se da, usa la de config.json del proyecto." },
      "--headed": {},
      "--max-cost": { matiz: "Tope en USD; al alcanzarlo, para y el mapa parcial sigue siendo válido." },
      "--max-iterations": { matiz: "Tope de vueltas del bucle; al alcanzarlo, para y lo dice en el informe." },
      "--max-repeated-action": { matiz: "Veces que se tolera la misma acción sin cambiar de pantalla antes de parar la corrida; 3 por defecto." },
      "--no-metrics": { matiz: "Esta corrida no queda registrada en metrics." },
      "--login": { matiz: "Intenta pasar el login antes de mapear." },
      "--no-login": { matiz: "No intenta login aunque haya receta o credenciales disponibles." },
      "--fresh-session": { matiz: "Ignora la sesión guardada aunque siga fresca; fuerza login de nuevo." },
      "--allow-writes": { matiz: "Permite enviar formularios sin preguntar — nunca tiene efecto en production." },
      "--no-writes": { matiz: "No envía ningún formulario ni pregunta." },
    },
    ejemplos: [
      { texto: 'run "<objetivo>"', explica: "Pide el objetivo en lenguaje normal.", plantilla: true },
      { texto: 'run "graba cómo doy de alta un registro"', explica: "Detecta que es una grabación y abre el navegador para ti.", plantilla: true },
    ],
    notas: [{ tipo: "aviso", texto: "La traducción de la frase gasta un LLM de por sí (con la modalidad configurada del proyecto), además del bucle de mapeo." }],
    ejes: EJE_MAPEADOR_LLM,
    palabrasClave: ["run", "lenguaje natural", "frase", "objetivo", "traducir"],
    incompatibles: [],
  },
  {
    ruta: ["agarraderos"],
    pestana: "Explorar",
    unaLinea: "Lee un map.json ya escrito y lista, pantalla por pantalla, qué elementos no tienen buen localizador estable y qué pedirle al equipo de desarrollo.",
    queHace: [
      "Recorre el mapa y separa los elementos con evidencia real de problema (`seen` sin nombre accesible, `ambiguous`, `positional`, o marcados `fragile`) de los que están simplemente sin probar todavía — solo reporta los primeros.",
      'Para cada uno sugiere la solución más barata para desarrollo: `aria-label` si falta nombre accesible, `data-testid` en el resto (localizador inestable o grupo de hermanos indistinguibles).',
    ],
    queDeja: [],
    cuandoUsarlo: ["Después de `map`/`run`, para convertir lo que quedó frágil o ambiguo en peticiones concretas al equipo de desarrollo."],
    cuandoNo: ["No navega ni gasta tokens: es lectura pura de un `map.json` ya existente. Si el mapa no existe todavía, primero hace falta `map`."],
    opciones: {},
    ejemplos: [{ texto: "agarraderos .agente-qa/map/map.json", explica: "Lista los elementos sin buen agarradero del mapa del proyecto.", plantilla: true }],
    notas: [{ tipo: "ok", texto: "Gratis y sin red: solo lee y clasifica lo que ya hay en disco." }],
    ejes: EJE_DETERMINISTA_SIN_AGENTE,
    palabrasClave: ["agarraderos", "localizador", "estable", "aria-label", "data-testid", "desarrollo"],
    incompatibles: [],
  },
  // ── Motor ──────────────────────────────────────────────────────────────────────────────
  {
    ruta: ["mcp", "tools"],
    pestana: "Motor",
    unaLinea: "Inventario verificado del servidor Playwright MCP: qué herramientas expone, quién las usa hoy y su grupo de capacidad.",
    queHace: [
      "Lista todas las herramientas que expone `@playwright/mcp`, marca cuáles llama el propio código por su cuenta, cuáles ve el LLM (el catálogo reducido y seguro que se le ofrece), y a qué grupo pertenece cada una (navegación básica, pestañas, pruebas, herramientas de desarrollador, almacenamiento...). Al pie, un recuento de los tres números.",
      "No cambia nada del mapa ni de ninguna exploración: es solo para mirar.",
    ],
    queDeja: [],
    cuandoUsarlo: ["Para confirmar qué puede hacer realmente el LLM (y qué no) antes de fiarte de una corrida.", "Al depurar por qué el agente no pudo hacer algo — comprobar si la herramienta ni siquiera está en su catálogo."],
    cuandoNo: [],
    opciones: { "--json": { matiz: "La misma lista y el mismo recuento, como JSON en vez de tabla de texto." } },
    ejemplos: [{ texto: "mcp tools", explica: "Tabla con todas las herramientas del servidor MCP.", plantilla: true }],
    notas: [{ tipo: "ok", texto: "Gratis: no llama a ningún LLM ni abre navegador." }],
    ejes: EJE_DETERMINISTA_SIN_AGENTE,
    palabrasClave: ["mcp", "tools", "herramientas", "inventario", "capacidad"],
    incompatibles: [],
  },
  {
    ruta: ["catalog"],
    pestana: "Motor",
    unaLinea: "Vuelca en JSON todos los comandos, subcomandos, argumentos y opciones reales del CLI, con sus descripciones tal cual están en el código.",
    queHace: [
      "Recorre la definición real de Commander (la misma que arma `--help`) y la vuelca como JSON: versión, opciones globales, y cada comando con su ruta, argumentos, opciones y subcomandos. La salida ES el documento: no aplica el `--json` global de eventos ni emite NDJSON.",
      "Es la fuente que sincroniza `Agente-QA-Web` (`npm run catalogo:sync`) para no mantener a mano una segunda copia de la lista de comandos, que se desincroniza en cuanto el CLI cambia.",
    ],
    queDeja: [],
    cuandoUsarlo: ["Para generar o comprobar la documentación de comandos de otra herramienta (como esta consola)."],
    cuandoNo: ["Para uso normal del CLI: no navega, no mapea, no configura nada."],
    opciones: { "--pretty": { matiz: "Indenta a 2 espacios; sin él, sale compacto en una sola línea (más cómodo para leer con `jq`)." } },
    ejemplos: [{ texto: "catalog --pretty", explica: "Vuelca el catálogo completo, legible.", plantilla: true }],
    notas: [{ tipo: "ok", texto: "Es la base del guard de esta misma web: si el CLI cambia y las fichas no se actualizan, los tests lo detectan." }],
    ejes: EJE_DETERMINISTA_SIN_AGENTE,
    palabrasClave: ["catalog", "catálogo", "comandos", "json", "documentación"],
    incompatibles: [],
  },
  // ── Operaciones pendientes: sin comando todavía (Redactar/Generar/Ejecutar/Reparar) ──────
  {
    ruta: ["redactor"],
    pestana: "Redactar",
    unaLinea: "Convertirá tu petición en Gherkin usando solo el vocabulario del map.json, preguntando cuando haya ambigüedad.",
    queHace: [
      "Leerá un map.json ya validado y traducirá lo que pidas a escenarios Gherkin (`*.feature`), sin poder citar nada que no esté en el mapa — si algo es ambiguo, preguntará en vez de inventar un paso.",
      "Su hermano `redactor-mcp` hará lo mismo a partir de los escenarios candidatos del mapa, pero sin preguntar, pensado para corridas desatendidas.",
    ],
    queDeja: ["`.agente-qa/features/*.feature` — todavía no se genera nada: este agente no existe aún."],
    cuandoUsarlo: ["Cuando quieras un feature Gherkin legible y auditable a partir de un mapa ya mapeado, sin escribirlo tú a mano."],
    cuandoNo: ["Hoy: no hay nada que lanzar — la pestaña Redactar todavía no tiene comando (ver `docs/plan-maestro.md`)."],
    opciones: {},
    ejemplos: [],
    notas: [{ tipo: "aviso", texto: "No existe todavía. Necesita un map.json validado (mapeador-mcp) como entrada — sin mapa, no hay de dónde sacar el vocabulario." }],
    ejes: { conductor: "llm-api", agente: "redactor", coste: "facturado", estado: "pendiente" },
    palabrasClave: ["redactor", "gherkin", "feature", "bdd"],
    incompatibles: [],
  },
  {
    ruta: ["generador"],
    pestana: "Generar",
    unaLinea: "Emitirá Page Objects y specs de Playwright a partir de un feature aprobado, con los localizadores reescritos desde el mapa.",
    queHace: [
      "Escribirá `*.page.ts` + `*.spec.ts` dentro de una plantilla acotada, y después reescribirá los localizadores citados desde el `map.json` de forma determinista — la garantía anti-invención viene de esa reescritura posterior, no de evitar el LLM.",
      "Su hermano `generador-mcp` escribirá specs y Page Objects sin plantilla, libre, para pantallas o casos que la plantilla no alcance (y por eso puede colar un localizador frágil que `generador` no dejaría pasar).",
    ],
    queDeja: ["`e2e/pages/*.page.ts` y `e2e/specs/*.spec.ts` — todavía no se genera nada: este agente no existe aún."],
    cuandoUsarlo: ["Cuando tengas un feature Gherkin aprobado y quieras los tests de Playwright reales."],
    cuandoNo: ["Hoy: no hay nada que lanzar — la pestaña Generar todavía no tiene comando."],
    opciones: {},
    ejemplos: [],
    notas: [{ tipo: "aviso", texto: "No existe todavía. Necesita un feature aprobado (redactor/redactor-mcp) y el map.json de origen." }],
    ejes: { conductor: "llm-api", agente: "generador", coste: "facturado", estado: "pendiente" },
    palabrasClave: ["generador", "page object", "spec", "playwright", "e2e"],
    incompatibles: [],
  },
  {
    ruta: ["ejecutor"],
    pestana: "Ejecutar",
    unaLinea: "Lanzará npx playwright test con reporter HTML y JSON, sin ningún LLM de por medio.",
    queHace: ["Ejecutará la suite generada, tal cual la lanzarías tú a mano, guardando el resultado en HTML (para mirar) y JSON (para que lo lea el Informador o un LLM)."],
    queDeja: ["Informe de Playwright (HTML + JSON) — todavía no se genera nada: este agente no existe aún."],
    cuandoUsarlo: ["Tras generar los tests, para comprobar si pasan."],
    cuandoNo: ["Hoy: no hay nada que lanzar — la pestaña Ejecutar todavía no tiene comando. Mientras tanto, `npx playwright test` a mano hace lo mismo sobre los tests que ya tengas."],
    opciones: {},
    ejemplos: [],
    notas: [{ tipo: "aviso", texto: "No existe todavía. Es determinista: no llama a ningún LLM, solo corre la suite." }],
    ejes: { conductor: "determinista", agente: "ejecutor", coste: "cero", estado: "pendiente" },
    palabrasClave: ["ejecutor", "playwright test", "correr", "suite", "reporter"],
    incompatibles: [],
  },
  {
    ruta: ["reparador"],
    pestana: "Reparar",
    unaLinea: "Ejecutará la suite, clasificará cada fallo y corregirá solo lo que sea culpa del test — hasta un límite de intentos.",
    queHace: [
      "Leerá la traza de Playwright (DOM, red y consola por paso, no solo el XML de resultados) para diagnosticar cada fallo, distinguiendo un test roto (localizador caducado, timing) de un fallo real de la aplicación — y solo tocará el test en el primer caso.",
      "Reejecutará tras cada corrección, hasta un tope de intentos, en vez de aplicar un parche a ciegas y darse por satisfecho.",
    ],
    queDeja: ["`e2e/specs/*.spec.ts` corregido + informe actualizado — todavía no se genera nada: este agente no existe aún."],
    cuandoUsarlo: ["Cuando la suite generada falla y quieres saber si es el test o la app antes de tocar nada a mano."],
    cuandoNo: ["Hoy: no hay nada que lanzar — la pestaña Reparar todavía no tiene comando."],
    opciones: {},
    ejemplos: [],
    notas: [
      { tipo: "aviso", texto: "No existe todavía. Necesita la suite generada y un fallo real que reproducir." },
      { tipo: "peligro", texto: "Cuando exista: nunca debe 'arreglar' un fallo real de la app cambiando el test para que pase igualmente — ese es justamente el riesgo que la clasificación previa evita." },
    ],
    ejes: { conductor: "llm-api", agente: "reparador", coste: "facturado", estado: "pendiente" },
    palabrasClave: ["reparador", "reparar", "fallo", "traza", "diagnóstico", "reintentar"],
    incompatibles: [],
  },
];
